<?php

/**
 * @file
 * Functions to support styling Admin toolbar.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function adminimal_admin_toolbar_preprocess_html(&$variables) {

  // Add adminimal-admin-toolbar class to the body.
  $variables['attributes']['class'][] = 'adminimal-admin-toolbar';

}

/**
 * Implements hook_page_attachments_alter().
 */
function adminimal_admin_toolbar_page_attachments_alter(array &$page) {

  // Attaches css assets globally.
  $page['#attached']['library'][] = 'adminimal_admin_toolbar/adminimal-admin-toolbar';
}
